-- bb2dash :: 030_bucket_private.sql
-- Phase 9 (docs/planning/62_PHASE9_sync_loop.md, "Migration 030 - bucket private").
--
-- The bb-files Storage bucket has been public: true since it was created on 2026-09-02
-- (migration 003). A public bucket serves every object from
--   /storage/v1/object/public/bb-files/<path>
-- with NO authentication at all, and the paths are derivable (course id / bucket / file
-- name - see v_file_layout). Verified 2026-09-10: an anonymous GET of
--   IST.352/lecture_slides/Introduction to SA&D - Part 1.1.pptx
-- returned HTTP 200. These are professors' copyrighted course materials; they must not be
-- world-readable.
--
-- Flipping public to false makes object reads go through RLS on storage.objects, where
-- migration 020 already left exactly two policies: the anon INSERT-only policy the browser
-- crawler / harvest jobs use, and bb_files_auth_all scoped to the owner. So:
--   * the web app is unaffected - queries.materials.ts already mints short-lived signed URLs
--     with createSignedUrl (signed URLs are generated by the Storage API and do not depend
--     on bucket publicity);
--   * the runbook's Storage POSTs are unaffected - they are governed by the INSERT policy,
--     not by public read;
--   * anonymous GETs of a known path now fail (400 "Object not found" - Storage does not
--     confirm existence to an unauthorized caller).
--
-- Additive and idempotent: re-running sets the same value.

update storage.buckets set public = false where id = 'bb-files';

-- Guard: fail loudly rather than silently leaving the bucket public if the row is missing
-- or the update was not permitted.
do $$
begin
  if not exists (select 1 from storage.buckets where id = 'bb-files' and public = false) then
    raise exception 'bb-files bucket is still public (or missing) after 030 - refusing to record this migration as applied';
  end if;
end $$;
