// bb2dash :: scripts/accept-proofs-db23.test.mjs
// Phase 23's twelve proofs (acceptance/23/proofs.json) against a real Postgres that lives in this
// process (PGlite, a dev dependency of scripts/). Nothing here reaches a network or the real
// database. Run, after `npm ci` in scripts/:
//   node --test scripts/accept-proofs-db23.test.mjs
//
// The tables are the ones the statements read, with the columns they name and no others, held
// against the migrations. The two views the statements read, v_inbox_queue (090) and
// v_inbox_apply_runs (187), and the function inbox_apply_held_items() (187), are the migrations'
// own text, cut out of the files and run here: a proof is held to the view as built.
//
// Pack 23's cases make their own rows and share nothing with pack 21's (accept-proofs-db.test.mjs).

import { after, before, beforeEach, test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

import { PGlite } from '@electric-sql/pglite';

import { EXIT, run } from './accept-proofs.mjs';
import { PACK_23, REPO, argvForPhase, clientOn, columnsOf } from './accept-proofs-kit.mjs';

/** table -> its columns here. The names are the migrations'; the types are the plain ones a statement needs. */
const TABLES = {
  agent_requests: {
    id: 'bigint generated always as identity primary key',
    created_at: 'timestamptz not null default now()',
    kind: 'text not null',
    scope: 'text',
    state: "text not null default 'queued'",
    params: "jsonb not null default '{}'",
    claimed_at: 'timestamptz',
    claimed_by: 'text',
    finished_at: 'timestamptz',
    result: 'jsonb',
  },
  attention_items: {
    id: 'bigint generated by default as identity primary key',
    raised_at: 'timestamptz not null default now()',
    raised_by: 'bigint',
    kind: 'text not null',
    course_id: 'text',
    entity: 'text',
    ref: 'text',
    field: 'text',
    from_value: 'jsonb',
    to_value: 'jsonb',
    question: "text not null default 'a question'",
    suggested: 'jsonb',
    state: "text not null default 'open'",
    resolved_at: 'timestamptz',
    resolution: 'jsonb',
    resolution_note: 'text',
    applied_at: 'timestamptz',
    archived_at: 'timestamptz',
    archived_by: 'text',
    decision: 'jsonb',
    decision_filed_at: 'timestamptz',
    decision_filed: 'jsonb',
  },
  inbox_apply_writes: {
    id: 'bigint generated always as identity primary key',
    request_id: 'bigint',
    item_id: 'bigint not null',
    table_name: 'text not null',
  },
  bb_files: { id: 'bigint primary key', session_id: 'bigint', superseded_by: 'bigint' },
  inbox_apply_holds: { item_id: 'bigint primary key', request_id: 'bigint not null', resolved_at: 'timestamptz' },
};

const ddlOf = ([table, columns]) => `create table public.${table} (${Object.entries(columns).map(([name, type]) => `${name} ${type}`).join(', ')});`;

/** The text of a migration between two marks, cut out to run here. A migration that moved a mark fails loudly. */
function cutOut(file, pattern) {
  const found = pattern.exec(fs.readFileSync(path.join(REPO, 'db', 'migrations', file), 'utf8'));
  assert.ok(found, `${file} holds the text this test runs`);
  return found[0];
}

const VIEW_INBOX_QUEUE = cutOut('090_attention_archive.sql', /create view v_inbox_queue[\s\S]*?where ai\.state in \('resolved', 'dismissed'\);/);
const VIEW_APPLY_RUNS = cutOut('187_inbox_apply_followups.sql', /create or replace view public\.v_inbox_apply_runs[\s\S]*?where a\.kind = 'inbox_feedback';/);
const FUNCTION_HELD_ITEMS = `${cutOut('187_inbox_apply_followups.sql', /create or replace function public\.inbox_apply_held_items\(\)[\s\S]*?as \$\$[\s\S]*?\$\$/)};`;

/** The columns of the view the proofs read, as the migration gives them. */
const APPLY_RUNS_COLUMNS = ['id', 'state', 'filed_by', 'after_request', 'claimed_by', 'created_at', 'claimed_at', 'finished_at', 'claude_started', 'error_code', 'archived_count', 'skip_ids'];

let db;

before(async () => {
  db = new PGlite();
  await db.waitReady;
  await db.exec(Object.entries(TABLES).map(ddlOf).join('\n'));
  await db.exec(VIEW_INBOX_QUEUE);
  await db.exec(VIEW_APPLY_RUNS);
  await db.exec(FUNCTION_HELD_ITEMS);
});

beforeEach(async () => {
  await db.exec(`truncate ${Object.keys(TABLES).map((table) => `public.${table}`).join(', ')} restart identity;`);
});

after(async () => {
  await db?.close();
});

/* ---------------------------------------------------------------------------------------------
 * What the cases are made of
 * ------------------------------------------------------------------------------------------ */

/** The run's start as the host hands it over, and the moments around it. */
const SINCE = '2026-10-09T14:00:00.000Z';
const IN_RUN = '2026-10-09T14:05:00Z';
const JUST_BEFORE = '2026-10-09T13:59:30Z';
const BEFORE_RUN = '2026-10-09T13:50:00Z';
const TAG = '1760018400123';
const OTHER_TAG = '1760018400999';
const APPLIER = 'inbox-apply-runner';

const DECISION_SCHEMA = 'inbox-decision/1';
const COURSE_TEXT = /syllabus|lecture|midterm/;

/** Runs one proof of the working tree's Phase 23 pack against the in-process database: its exit code and its one line. */
async function prove(name, params = {}) {
  const out = [];
  const err = [];
  const code = await run(argvForPhase('23', name, params), {
    out: (line) => out.push(line),
    err: (line) => err.push(line),
    readPack: () => PACK_23,
    clientFactory: async () => clientOn(db),
  });
  assert.equal(out.length, 1, 'one line is printed');
  assert.doesNotMatch(out[0], COURSE_TEXT);
  const line = JSON.parse(out[0]);
  return { code, line, detail: line.detail, blocked: line.blocked === true, why: err.join('\n') };
}

async function addRequest({ kind = 'inbox_feedback', state = 'done', params = {}, createdAt = IN_RUN, claimedBy = null, claimedAfterS = null, finishedAfterS = null, result = null }) {
  const row = await db.query(
    `insert into public.agent_requests (kind, state, params, created_at, claimed_by, claimed_at, finished_at, result)
     values ($1, $2, $3::jsonb, $4::timestamptz, $5,
             case when $6::integer is null then null else $4::timestamptz + make_interval(secs => $6::integer) end,
             case when $7::integer is null then null else $4::timestamptz + make_interval(secs => $7::integer) end,
             $8::jsonb)
     returning id`,
    [kind, state, JSON.stringify(params), createdAt, claimedBy, claimedAfterS, finishedAfterS, result === null ? null : JSON.stringify(result)],
  );
  return row.rows[0].id;
}

/** A sync request the sync container took and closed. */
const addSync = (more = {}) => addRequest({ kind: 'sync', state: 'done', claimedBy: 'sync-runner', claimedAfterS: 15, finishedAfterS: 120, ...more });

/** An Inbox apply request: `trigger` null is a press of the button, which files a request with no trigger. */
function addApply({ trigger = 'sync', after = null, state = 'done', claudeStarted = false, error = null, createdAt = IN_RUN, claimedBy = APPLIER, claimedAfterS = 12, finishedAfterS = 40, archived = 2 } = {}) {
  const params = trigger === null ? {} : { trigger, after };
  const result = state === 'done' || state === 'failed' ? { lines: ['A line'], archived, claude: { started: claudeStarted }, ...(error === null ? {} : { error }) } : null;
  return addRequest({
    kind: 'inbox_feedback',
    state,
    params,
    createdAt,
    claimedBy: state === 'queued' ? null : claimedBy,
    claimedAfterS: state === 'queued' ? null : claimedAfterS,
    finishedAfterS: state === 'done' || state === 'failed' ? finishedAfterS : null,
    result,
  });
}

/**
 * One Inbox item. The defaults are a test question as `inbox_accept_question` raises it, answered
 * and archived by `by` (a request id) in the bucket given; `by: null` leaves it open, `state`
 * overrides the state of an answered one that is not archived yet.
 */
async function addItem({
  label, tag = TAG, id = null, kind = 'stack_must_confirm', by = null, bucket = 'recorded_elsewhere', state = null, raisedAt = IN_RUN,
  resolution = { value: 'a word', value_type: 'text' }, withNote = false, answered = true, entity = 'agent_request', course = null,
  ref = `accept/${tag}/${label}`, filed = null, schema = DECISION_SCHEMA, appliedAt = null, field = null,
}) {
  const archived = by !== null;
  const itemState = state ?? (archived ? 'archived' : answered ? (kind === 'data_gap' && resolution?.dismissed ? 'dismissed' : 'resolved') : 'open');
  const row = await db.query(
    `insert into public.attention_items (id, raised_at, kind, course_id, entity, ref, field, state, resolved_at, resolution, resolution_note,
                                         applied_at, archived_at, archived_by, decision, decision_filed_at, decision_filed)
     values (coalesce($1::bigint, nextval(pg_get_serial_sequence('public.attention_items', 'id'))), $2::timestamptz, $3, $4, $5, $6, $7, $8,
             case when $9::boolean then $2::timestamptz + interval '1 minute' end,
             case when $9::boolean then $10::jsonb end,
             case when $11::boolean then 'a reason' end,
             $12::timestamptz,
             case when $13::boolean then $2::timestamptz + interval '4 minutes' end,
             case when $13::boolean then 'inbox-apply request ' || $14::text end,
             case when $13::boolean then jsonb_build_object('schema', $15::text, 'bucket', $16::text) end,
             case when $17::jsonb is null then null else $2::timestamptz + interval '1 hour' end,
             $17::jsonb)
     returning id`,
    [id, raisedAt, kind, course, entity, ref, field, itemState, answered, JSON.stringify(resolution), withNote, appliedAt, archived, by === null ? null : String(by), schema, bucket, filed === null ? null : JSON.stringify(filed)],
  );
  return row.rows[0].id;
}

/** An item of Stack's own, answered and waiting in the queue. */
const addWaitingAnswer = (more = {}) => addItem({ label: 'x', ref: 'assignment/ist-323/a1', entity: 'assignment', course: 'ist323', kind: 'conflict', resolution: { accept: 'keep' }, ...more });

/* ---------------------------------------------------------------------------------------------
 * The tables and the views are the migrations'
 * ------------------------------------------------------------------------------------------ */

test('every table and column these cases are made of is in the migrations, and the view the proofs read has the columns they name', () => {
  for (const [table, columns] of Object.entries(TABLES)) {
    for (const column of Object.keys(columns)) assert.ok(columnsOf(table).has(column), `${table}.${column}`);
  }
  assert.deepEqual([...columnsOf('v_inbox_apply_runs')], APPLY_RUNS_COLUMNS);
  for (const column of ['id', 'kind', 'course_id', 'entity', 'ref', 'resolved_at', 'applied_at', 'was_applied', 'has_note']) {
    assert.ok(columnsOf('v_inbox_queue').has(column), `v_inbox_queue.${column}`);
  }
});

test('pack 23 holds the twelve proofs, by name', () => {
  assert.deepEqual(Object.keys(PACK_23).sort(), [
    'applied-from-button', 'apply-idle', 'apply-quiet', 'decisions-filed', 'nothing-written', 'questions-raised',
    'recorded-after-sync', 'request-taken-after', 'request-waiting', 'sync-taken', 'test-decisions-skipped', 'transform-answers',
  ]);
});

/* ---------------------------------------------------------------------------------------------
 * Step 0 and the stop: apply-quiet, apply-idle
 * ------------------------------------------------------------------------------------------ */

const LOGIN_ITEM = { label: 'x', ref: 'sync-login-required', entity: 'agent_request', answered: false };

test('apply-quiet: nothing open, nothing of his waiting and no login item passes; each of those blocks, and the held ones are counted', async () => {
  const quiet = await prove('apply-quiet');
  assert.equal(quiet.code, EXIT.pass, quiet.why);
  assert.deepEqual(quiet.detail, { requests_open: 0, first_open_request_id: null, answers_waiting: 0, answers_held: 0, login_items_open: 0 });

  // None of these counts: a request that ended, an open test question, a test question left answered, a login item that closed.
  await addSync();
  await addApply();
  await addItem({ label: 'note', answered: false });
  await addItem({ label: 'confirm', tag: OTHER_TAG });
  await addItem({ ...LOGIN_ITEM, by: 1, bucket: 'recorded_elsewhere' });
  assert.equal((await prove('apply-quiet')).code, EXIT.pass);

  // A sync or an Inbox apply request that waits or runs blocks, whatever its age.
  const waiting = await addRequest({ kind: 'sync', state: 'queued', createdAt: BEFORE_RUN });
  const blockedBySync = await prove('apply-quiet');
  assert.deepEqual([blockedBySync.code, blockedBySync.blocked, blockedBySync.detail.requests_open, blockedBySync.detail.first_open_request_id], [EXIT.blocked, true, 1, waiting]);
  await db.query("update public.agent_requests set state = 'failed' where id = $1", [waiting]);
  const claimed = await addApply({ state: 'claimed' });
  assert.deepEqual([(await prove('apply-quiet')).code, (await prove('apply-quiet')).detail.first_open_request_id], [EXIT.blocked, claimed]);
  await db.query("update public.agent_requests set state = 'done' where id = $1", [claimed]);
  assert.equal((await prove('apply-quiet')).code, EXIT.pass);

  // An answer of his, held or not, blocks (a press of Apply answers tries held answers), and the record says which.
  const answer = await addWaitingAnswer();
  const answered = await prove('apply-quiet');
  assert.deepEqual([answered.code, answered.detail.answers_waiting, answered.detail.answers_held], [EXIT.blocked, 1, 0]);
  const stamp = (await db.query('select resolved_at from public.attention_items where id = $1', [answer])).rows[0].resolved_at;
  await db.query('insert into public.inbox_apply_holds (item_id, request_id, resolved_at) values ($1, 1, $2)', [answer, stamp]);
  const held = await prove('apply-quiet');
  assert.deepEqual([held.code, held.detail.answers_waiting, held.detail.answers_held], [EXIT.blocked, 1, 1]);
  // A hold for an older answer holds nothing.
  await db.query("update public.inbox_apply_holds set resolved_at = resolved_at - interval '1 day'");
  assert.equal((await prove('apply-quiet')).detail.answers_held, 0);
  await db.query('delete from public.attention_items');

  // A Blackboard login that is dead blocks: an open sync-login-required item.
  await addItem(LOGIN_ITEM);
  const login = await prove('apply-quiet');
  assert.deepEqual([login.code, login.detail.login_items_open], [EXIT.blocked, 1]);
});

test('apply-idle: no Inbox apply request queued or claimed passes; one that is blocks, a sync or a finished one does not', async () => {
  const idle = await prove('apply-idle');
  assert.equal(idle.code, EXIT.pass, idle.why);
  assert.deepEqual(idle.detail, { requests_open: 0, first_open_request_id: null });
  await addSync({ state: 'claimed' });
  await addApply({ state: 'done' });
  assert.equal((await prove('apply-idle')).code, EXIT.pass);
  const queued = await addApply({ state: 'queued', trigger: null });
  const one = await prove('apply-idle');
  assert.deepEqual([one.code, one.blocked, one.detail.requests_open, one.detail.first_open_request_id], [EXIT.blocked, true, 1, queued]);
  await db.query("update public.agent_requests set state = 'claimed' where id = $1", [queued]);
  assert.equal((await prove('apply-idle')).code, EXIT.blocked);
});

/* ---------------------------------------------------------------------------------------------
 * Step 1: questions-raised
 * ------------------------------------------------------------------------------------------ */

/** The four test questions as step 1 leaves them after the walk: the first two answered, all four of this run. */
async function raiseFour(more = {}) {
  const apply = await addApply();
  const confirm = await addItem({ label: 'confirm', by: apply, bucket: 'recorded_elsewhere', ...more.confirm });
  const dismiss = await addItem({ label: 'dismiss', kind: 'data_gap', by: apply, bucket: 'dismissed', resolution: { dismissed: true }, ...more.dismiss });
  const note = await addItem({ label: 'note', by: apply, withNote: true, ...more.note });
  const offline = await addItem({ label: 'offline', kind: 'data_gap', answered: false, ...more.offline });
  return { confirm, dismiss, note, offline };
}

const raisedParams = (items, more = {}) => ({
  confirm_item: String(items.confirm), dismiss_item: String(items.dismiss), note_item: String(items.note), offline_item: String(items.offline), since: SINCE, ...more,
});

test('questions-raised: the four, raised in this run with the right kinds and labels, the first two answered with no reason, passes', async () => {
  const items = await raiseFour();
  const passed = await prove('questions-raised', raisedParams(items));
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    [passed.detail.items_found, passed.detail.shaped_and_raised_in_this_run, passed.detail.answers_right, passed.detail.run_tags],
    [4, 4, 2, 1],
  );
  // The 60 seconds are for a host clock that runs ahead of the database's.
  await db.query('update public.attention_items set raised_at = $1::timestamptz where id = $2', [JUST_BEFORE, items.offline]);
  assert.equal((await prove('questions-raised', raisedParams(items))).code, EXIT.pass);
  await questionsRaisedCase2();
});

/** Empties the tables the cases fill, and builds what the case needs on them. */
async function rebuilt(build) {
  await db.exec('truncate public.attention_items, public.agent_requests, public.inbox_apply_writes, public.inbox_apply_holds, public.bb_files restart identity');
  return build();
}

/** an old row, a wrong kind or label, another tag, a reason, a missing answer or a row that is not a test question fails */
async function questionsRaisedCase2() {
  const bad = async (why, change) => {
    const items = await rebuilt(() => raiseFour());
    await change(items);
    assert.equal((await prove('questions-raised', raisedParams(items))).code, EXIT.fail, why);
  };
  const set = (column, value, label) => (items) => db.query(`update public.attention_items set ${column} = $1 where id = $2`, [value, items[label]]);
  await bad('raised before the run', (items) => db.query('update public.attention_items set raised_at = $1::timestamptz where id = $2', [BEFORE_RUN, items.note]));
  await bad('dismiss raised as a stack_must_confirm', set('kind', 'stack_must_confirm', 'dismiss'));
  await bad('confirm raised as a data_gap', set('kind', 'data_gap', 'confirm'));
  await bad('the third is labelled as the second', set('ref', `accept/${TAG}/dismiss`, 'note'));
  await bad('another run tag', set('ref', `accept/${OTHER_TAG}/offline`, 'offline'));
  await bad('confirmed with a reason', set('resolution_note', 'a reason', 'confirm'));
  await bad('dismissed with a reason', set('resolution_note', 'a reason', 'dismiss'));
  await bad('confirm never answered', (items) => db.query('update public.attention_items set resolved_at = null, resolution = null where id = $1', [items.confirm]));
  await bad('dismiss answered with a value, not dismissed', (items) => db.query(`update public.attention_items set resolution = '{"value": "x"}'::jsonb where id = $1`, [items.dismiss]));
  await bad('a row of a course', set('course_id', 'ist323', 'offline'));
  await bad('an item that is no test question', set('ref', 'sync-login-required', 'offline'));
  // A row that is not there is no row.
  const items = await rebuilt(() => raiseFour());
  const missing = await prove('questions-raised', raisedParams(items, { offline_item: '999999' }));
  assert.equal(missing.code, EXIT.fail);
  assert.equal(missing.detail.items_found, 3);
}

/* ---------------------------------------------------------------------------------------------
 * Step 2: sync-taken
 * ------------------------------------------------------------------------------------------ */

const LOGIN_RAISED = { label: 'x', ref: 'sync-login-required', entity: 'agent_request', answered: false };

test("sync-taken: this run's sync, claimed by the sync container, passes; blocked, not failed, when it closed on a dead Blackboard login", async () => {
  const sync = await addSync();
  const passed = await prove('sync-taken', { request: String(sync), since: SINCE });
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    { ...passed.detail, created_at: null, claimed_at: null, finished_at: null },
    {
      request_id: sync, request_kind: 'sync', request_state: 'done', created_at: null, claimed_at: null, claimed_by: 'sync-runner', finished_at: null,
      asked_in_this_run: true, taken_by_the_runner: true, login_item_raised_in_this_run: false,
    },
  );
  const params = (request) => ({ request: String(request), since: SINCE });
  // Taken by a session or by nobody, from before the run, or not a sync: no.
  assert.equal((await prove('sync-taken', params(await addSync({ claimedBy: 'a-session' })))).code, EXIT.fail);
  assert.equal((await prove('sync-taken', params(await addRequest({ kind: 'sync', state: 'queued' })))).code, EXIT.fail);
  assert.equal((await prove('sync-taken', params(await addSync({ createdAt: BEFORE_RUN })))).code, EXIT.fail);
  assert.equal((await prove('sync-taken', params(await addApply()))).code, EXIT.fail);
  assert.equal((await prove('sync-taken', params(999))).detail.error, 'expected_one_row');
  // The sync closed failed and the login item was raised in this run: the login is dead, the run is repeated.
  // Taken is all this proof says: a sync that failed for another reason is judged by the next step.
  const dead = await addSync({ state: 'failed' });
  assert.equal((await prove('sync-taken', params(dead))).code, EXIT.pass);
  await addItem({ ...LOGIN_RAISED, raisedAt: IN_RUN });
  const blocked = await prove('sync-taken', params(dead));
  assert.deepEqual([blocked.code, blocked.blocked, blocked.detail.login_item_raised_in_this_run], [EXIT.blocked, true, true]);
  // A login item from before the run says nothing about this one.
  await db.query('update public.attention_items set raised_at = $1::timestamptz', [BEFORE_RUN]);
  assert.equal((await prove('sync-taken', params(dead))).code, EXIT.pass);
});

/* ---------------------------------------------------------------------------------------------
 * Step 3: recorded-after-sync
 * ------------------------------------------------------------------------------------------ */

/** The sync, the apply request it filed, and the two answered questions that request archived. */
async function afterSync({ apply = {}, first = {}, second = {} } = {}) {
  const sync = await addSync();
  const request = await addApply({ trigger: 'sync', after: sync, ...apply });
  const confirm = await addItem({ label: 'confirm', by: request, bucket: 'recorded_elsewhere', ...first });
  const dismiss = await addItem({ label: 'dismiss', kind: 'data_gap', by: request, bucket: 'dismissed', resolution: { dismissed: true }, ...second });
  return { sync, request, confirm, dismiss };
}

const afterSyncParams = (world) => ({ sync_request: String(world.sync), first_item: String(world.confirm), second_item: String(world.dismiss), since: SINCE });

test('recorded-after-sync: the sync done, one apply request it filed, taken by the worker and done, archived the two in their buckets', async () => {
  const world = await afterSync();
  const passed = await prove('recorded-after-sync', afterSyncParams(world));
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    [passed.detail.sync_state, passed.detail.apply_requests_naming_it, passed.detail.apply_request_id, passed.detail.apply_filed_by, passed.detail.apply_state],
    ['done', 1, world.request, 'sync', 'done'],
  );
  assert.deepEqual([passed.detail.first_bucket, passed.detail.second_bucket], ['recorded_elsewhere', 'dismissed']);
  assert.equal(passed.detail.apply_claude_started, false);
  await recordedAfterSyncCase2();
  await recordedAfterSyncCase3();
});

/** a missing, doubled, button-filed or untaken request, a wrong bucket or an item archived by another request fails */
async function recordedAfterSyncCase2() {
  const bad = async (why, make) => {
    const world = await rebuilt(make);
    const result = await prove('recorded-after-sync', afterSyncParams(world));
    assert.equal(result.code, EXIT.fail, why);
    assert.equal(result.blocked, false, why);
  };
  await bad('the sync is not done', () => afterSync().then(async (w) => { await db.query("update public.agent_requests set state = 'failed' where id = $1", [w.sync]); return w; }));
  await bad('the apply request was filed by a follow-up, not by the sync', () => afterSync({ apply: { trigger: 'followup' } }));
  await bad('the apply request was never taken', () => afterSync({ apply: { claimedBy: 'a-session' } }));
  await bad('the apply request failed', () => afterSync({ apply: { state: 'failed', error: 'cli_error' } }));
  await bad('two apply requests name the sync', () => afterSync().then(async (w) => { await addApply({ trigger: 'sync', after: w.sync }); return w; }));
  await bad('no apply request names the sync', () => afterSync().then(async (w) => { await db.query("update public.agent_requests set params = '{}'::jsonb where kind = 'inbox_feedback'"); return w; }));
  await bad('the apply request is from before the run', () => afterSync({ apply: { createdAt: BEFORE_RUN } }));
  await bad('the first is in the wrong bucket', () => afterSync({ first: { bucket: 'dismissed' } }));
  await bad('the second is in the wrong bucket', () => afterSync({ second: { bucket: 'recorded_elsewhere' } }));
  await bad('the first was archived by another request', () => afterSync().then(async (w) => { await db.query("update public.attention_items set archived_by = 'inbox-apply request 999' where id = $1", [w.confirm]); return w; }));
  await bad('the second is not archived', () => afterSync().then(async (w) => { await db.query("update public.attention_items set state = 'dismissed', archived_by = null, decision = null where id = $1", [w.dismiss]); return w; }));
}

/** blocked, not failed, when the apply request met the plan or the day: the usage limit or the daily cap */
async function recordedAfterSyncCase3() {
  for (const error of ['daily_cap', 'usage_limit']) {
    await db.exec('truncate public.attention_items, public.agent_requests restart identity');
    const world = await afterSync({ apply: { state: 'failed', error } });
    const capped = await prove('recorded-after-sync', afterSyncParams(world));
    assert.deepEqual([capped.code, capped.blocked, capped.detail.apply_error_code], [EXIT.blocked, true, error]);
  }
  // Any other error is red.
  await db.exec('truncate public.attention_items, public.agent_requests restart identity');
  assert.equal((await prove('recorded-after-sync', afterSyncParams(await afterSync({ apply: { state: 'failed', error: 'timed_out' } })))).code, EXIT.fail);
}

/* ---------------------------------------------------------------------------------------------
 * Step 4: nothing-written
 * ------------------------------------------------------------------------------------------ */

test('nothing-written: no row of the write log for the two questions of this run passes; a write for either fails', async () => {
  const world = await afterSync();
  const params = { first_item: String(world.confirm), second_item: String(world.dismiss), since: SINCE };
  const passed = await prove('nothing-written', params);
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual([passed.detail.items_found, passed.detail.raised_in_this_run, passed.detail.writes_logged], [2, 2, 0]);
  // A write for a third item is not about these two.
  await db.query("insert into public.inbox_apply_writes (request_id, item_id, table_name) values (1, 999, 'assignments')");
  assert.equal((await prove('nothing-written', params)).code, EXIT.pass);
  await db.query("insert into public.inbox_apply_writes (request_id, item_id, table_name) values ($1, $2, 'assignments')", [world.request, world.dismiss]);
  const written = await prove('nothing-written', params);
  assert.deepEqual([written.code, written.detail.writes_logged], [EXIT.fail, 1]);
  await nothingWrittenCase2();
});

/** a row that is no test question of this run proves nothing, and fails */
async function nothingWrittenCase2() {
  const world = await afterSync();
  const params = { first_item: String(world.confirm), second_item: String(world.dismiss), since: SINCE };
  await db.query("update public.attention_items set course_id = 'ist323' where id = $1", [world.dismiss]);
  assert.equal((await prove('nothing-written', params)).code, EXIT.fail);
  await db.query('update public.attention_items set course_id = null where id = $1', [world.dismiss]);
  await db.query('update public.attention_items set raised_at = $1::timestamptz where id = $2', [BEFORE_RUN, world.confirm]);
  assert.equal((await prove('nothing-written', params)).code, EXIT.fail);
  assert.equal((await prove('nothing-written', { ...params, first_item: '999999' })).code, EXIT.fail);
}

/* ---------------------------------------------------------------------------------------------
 * Step 6: applied-from-button
 * ------------------------------------------------------------------------------------------ */

/** The sync's apply request, then the button's request that started Claude and archived the third question. */
async function fromButton({ apply = {}, note = {} } = {}) {
  const sync = await addSync();
  await addApply({ trigger: 'sync', after: sync });
  const request = await addApply({ trigger: null, claudeStarted: true, createdAt: '2026-10-09T14:12:00Z', finishedAfterS: 150, archived: 1, ...apply });
  const item = await addItem({ label: 'note', by: request, withNote: true, ...note });
  return { sync, request, item };
}

const buttonParams = (world, more = {}) => ({ request: String(world.request), item: String(world.item), after: String(world.sync), since: SINCE, ...more });

test('applied-from-button: a later request of this run, filed from the button, that started Claude and closed done, archived the third question', async () => {
  const world = await fromButton();
  const passed = await prove('applied-from-button', buttonParams(world));
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    [passed.detail.request_filed_by, passed.detail.request_claude_started, passed.detail.request_state, passed.detail.item_archived_by_it, passed.detail.writes_logged],
    ['button', true, 'done', true, 0],
  );
  // The planner and the course tables are not touched by a test question: a write for it fails the step.
  await db.query("insert into public.inbox_apply_writes (request_id, item_id, table_name) values ($1, $2, 'assignment_progress')", [world.request, world.item]);
  assert.equal((await prove('applied-from-button', buttonParams(world))).code, EXIT.fail);
  await appliedFromButtonCase2();
  await appliedFromButtonCase3();
});

/** a request a sync filed, one that never started Claude or failed, an older id or another archiver fails */
async function appliedFromButtonCase2() {
  const bad = async (why, make, more = {}) => {
    const world = await rebuilt(make);
    const result = await prove('applied-from-button', buttonParams(world, more));
    assert.equal(result.code, EXIT.fail, why);
    assert.equal(result.blocked, false, why);
  };
  await bad('filed by a sync', () => fromButton({ apply: { trigger: 'sync', after: 1 } }));
  await bad('Claude never started', () => fromButton({ apply: { claudeStarted: false } }));
  await bad('the request failed', () => fromButton({ apply: { state: 'failed', error: 'not_applied' } }));
  await bad('taken by a session', () => fromButton({ apply: { claimedBy: 'a-session' } }));
  await bad('the request is from before the run', () => fromButton({ apply: { createdAt: BEFORE_RUN } }));
  await bad('the item was archived by another request', () => fromButton().then(async (w) => { await db.query("update public.attention_items set archived_by = 'inbox-apply request 999' where id = $1", [w.item]); return w; }));
  await bad('the item is not archived', () => fromButton().then(async (w) => { await db.query("update public.attention_items set state = 'resolved', archived_by = null where id = $1", [w.item]); return w; }));
  await bad('the item carries no reason', () => fromButton({ note: { withNote: false } }));
  // One request cannot stand for both presses: it must be the later one.
  await bad('not later than the sync', () => fromButton(), { after: '999' });
}

/** blocked, not failed, when the request met the plan or the day: the item is then still waiting */
async function appliedFromButtonCase3() {
  for (const error of ['daily_cap', 'usage_limit']) {
    await db.exec('truncate public.attention_items, public.agent_requests restart identity');
    const world = await fromButton({ apply: { state: 'failed', error, archived: 0 }, note: { by: null } });
    const capped = await prove('applied-from-button', buttonParams(world));
    assert.deepEqual([capped.code, capped.blocked, capped.detail.request_error_code], [EXIT.blocked, true, error]);
  }
}

/* ---------------------------------------------------------------------------------------------
 * Steps 7a and 7b: request-waiting, request-taken-after
 * ------------------------------------------------------------------------------------------ */

/** The press of the button while the worker is stopped: a queued request and the fourth question, answered and waiting. */
async function pressedWhileStopped(more = {}) {
  const request = await addApply({ trigger: null, state: 'queued', createdAt: IN_RUN, ...more.request });
  const item = await addItem({ label: 'offline', kind: 'data_gap', resolution: { dismissed: true }, ...more.item });
  return { request, item };
}

test('request-waiting: the button filed it, nobody has taken it, the fourth question still waits answered: passes; taken or ended fails', async () => {
  const world = await pressedWhileStopped();
  const params = { request: String(world.request), item: String(world.item), since: SINCE };
  const passed = await prove('request-waiting', params);
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    [passed.detail.request_state, passed.detail.request_claimed_by, passed.detail.request_filed_by, passed.detail.item_waiting, passed.detail.asked_in_this_run],
    ['queued', null, 'button', true, true],
  );
  assert.equal(typeof passed.detail.waited_s, 'number');
  const fails = async (why, change) => {
    await change();
    assert.equal((await prove('request-waiting', params)).code, EXIT.fail, why);
  };
  await fails('the item was archived', () => db.query("update public.attention_items set state = 'archived' where id = $1", [world.item]));
  await db.query("update public.attention_items set state = 'dismissed' where id = $1", [world.item]);
  await fails('claimed', () => db.query("update public.agent_requests set state = 'claimed', claimed_by = $1, claimed_at = now() where id = $2", [APPLIER, world.request]));
  await db.query("update public.agent_requests set state = 'queued', claimed_by = null, claimed_at = null where id = $1", [world.request]);
  await fails('filed by a sync', () => db.query(`update public.agent_requests set params = '{"trigger": "sync", "after": 1}'::jsonb where id = $1`, [world.request]));
  await db.query("update public.agent_requests set params = '{}'::jsonb where id = $1", [world.request]);
  await fails('from before the run', () => db.query('update public.agent_requests set created_at = $1::timestamptz where id = $2', [BEFORE_RUN, world.request]));
});

/** The waiting request after the worker came back: taken `claimedAfterS` seconds after it was filed, done, the item archived as dismissed. */
async function takenAfter({ claimedAfterS = 95, request = {}, item = {} } = {}) {
  const id = await addApply({ trigger: null, state: 'done', createdAt: IN_RUN, claimedAfterS, finishedAfterS: claimedAfterS + 8, archived: 1, ...request });
  const answered = await addItem({ label: 'offline', kind: 'data_gap', by: id, bucket: 'dismissed', resolution: { dismissed: true }, ...item });
  return { request: id, item: answered };
}

const takenParams = (world, more = {}) => ({ request: String(world.request), item: String(world.item), since: SINCE, min_wait_s: '75', ...more });

test('request-taken-after: taken at least 75 seconds after it was filed, done, and it archived the fourth question as dismissed: passes', async () => {
  const world = await takenAfter();
  const passed = await prove('request-taken-after', takenParams(world));
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual(
    [passed.detail.request_state, passed.detail.request_claimed_by, passed.detail.waited_s, passed.detail.min_wait_s, passed.detail.item_archived_by_it, passed.detail.bucket],
    ['done', APPLIER, 95, 75, true, 'dismissed'],
  );
  const bad = async (why, make) => {
    assert.equal((await prove('request-taken-after', takenParams(await rebuilt(make)))).code, EXIT.fail, why);
  };
  await bad('taken before the wait was over', () => takenAfter({ claimedAfterS: 20 }));
  await bad('filed by a sync', () => takenAfter({ request: { trigger: 'sync', after: 1 } }));
  await bad('taken by a session', () => takenAfter({ request: { claimedBy: 'a-session' } }));
  await bad('the request failed', () => takenAfter({ request: { state: 'failed', error: 'cli_error' } }));
  await bad('another bucket', () => takenAfter({ item: { bucket: 'recorded_elsewhere' } }));
  await bad('archived by another request', () => takenAfter().then(async (w) => { await db.query("update public.attention_items set archived_by = 'inbox-apply request 999' where id = $1", [w.item]); return w; }));
  await bad('from before the run', () => takenAfter({ request: { createdAt: BEFORE_RUN } }));
  // Blocked, not failed, at the plan's limit or the day's cap.
  await db.exec('truncate public.attention_items, public.agent_requests restart identity');
  const capped = await prove('request-taken-after', takenParams(await takenAfter({ request: { state: 'failed', error: 'daily_cap' }, item: { by: null } })));
  assert.deepEqual([capped.code, capped.blocked], [EXIT.blocked, true]);
});

/* ---------------------------------------------------------------------------------------------
 * Step 5: test-decisions-skipped, decisions-filed
 * ------------------------------------------------------------------------------------------ */

const SKIPPED = { skipped: true, why: 'a test question of an acceptance run' };
const NOTE_FILED = { note_path: 'projects/decisions/2026-10-09.md' };

async function archivedFour(filed = SKIPPED, override = {}) {
  const apply = await addApply();
  const make = (label, kind, more = {}) => addItem({ label, kind, by: apply, filed, ...more, ...override[label] });
  return {
    confirm: await make('confirm', 'stack_must_confirm'),
    dismiss: await make('dismiss', 'data_gap', { resolution: { dismissed: true }, bucket: 'dismissed' }),
    note: await make('note', 'stack_must_confirm', { withNote: true }),
    offline: await make('offline', 'data_gap', { resolution: { dismissed: true }, bucket: 'dismissed' }),
  };
}

test("test-decisions-skipped: the run's four decisions are marked skipped with no note path; a note, an unfiled one or an old one fails", async () => {
  const items = await archivedFour();
  const passed = await prove('test-decisions-skipped', raisedParams(items));
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual([passed.detail.items_found, passed.detail.skipped_with_no_note], [4, 4]);
  const bad = async (why, label, sql, values) => {
    const fresh = await rebuilt(() => archivedFour());
    await db.query(sql, [...values, fresh[label]]);
    const failed = await prove('test-decisions-skipped', raisedParams(fresh));
    assert.equal(failed.code, EXIT.fail, why);
    assert.equal(failed.detail.skipped_with_no_note, 3, why);
  };
  await bad('one was filed with a note', 'note', 'update public.attention_items set decision_filed = $1::jsonb where id = $2', [JSON.stringify(NOTE_FILED)]);
  await bad('one was skipped but also carries a note path', 'note', 'update public.attention_items set decision_filed = $1::jsonb where id = $2', [JSON.stringify({ ...SKIPPED, ...NOTE_FILED })]);
  await bad('one is still unfiled', 'confirm', 'update public.attention_items set decision_filed_at = null, decision_filed = null where id = $1', []);
  await bad('one is from an earlier run', 'offline', 'update public.attention_items set raised_at = $1::timestamptz where id = $2', [BEFORE_RUN]);
  await bad('one is no decision record', 'dismiss', `update public.attention_items set decision = '{"closed_itself": true}'::jsonb where id = $1`, []);
});

test('decisions-filed: no archived decision is left unfiled and item 3782 is skipped passes; an unfiled one, or 3782 filed with a note, fails', async () => {
  const empty = await prove('decisions-filed');
  assert.equal(empty.code, EXIT.fail, 'there is no item 3782 to be skipped');
  assert.equal(empty.detail.item_3782_skipped, false);
  await addItem({ id: 3782, label: 'x', ref: 'inbox-test', entity: 'assignment', course: 'ist323', by: 1, filed: SKIPPED });
  const items = await archivedFour(NOTE_FILED);
  const passed = await prove('decisions-filed');
  assert.equal(passed.code, EXIT.pass, passed.why);
  assert.deepEqual([passed.detail.unfiled, passed.detail.item_3782_skipped, passed.detail.filed_with_a_note_path, passed.detail.skipped], [0, true, 4, 1]);
  // A row that is not a decision record, or is not archived, is not a decision.
  await addItem({ label: 'x', ref: 'a/b', entity: 'assignment', course: 'ist323', by: 1, schema: 'something-else' });
  assert.equal((await prove('decisions-filed')).code, EXIT.pass);
  await db.query('update public.attention_items set decision_filed_at = null, decision_filed = null where id = $1', [items.offline]);
  const unfiled = await prove('decisions-filed');
  assert.deepEqual([unfiled.code, unfiled.detail.unfiled], [EXIT.fail, 1]);
  await db.query('update public.attention_items set decision_filed_at = now(), decision_filed = $1::jsonb where id = $2', [JSON.stringify(NOTE_FILED), items.offline]);
  assert.equal((await prove('decisions-filed')).code, EXIT.pass);
  await db.query('update public.attention_items set decision_filed = $1::jsonb where id = 3782', [JSON.stringify(NOTE_FILED)]);
  assert.equal((await prove('decisions-filed')).code, EXIT.fail);
});

/* ---------------------------------------------------------------------------------------------
 * Step 9: transform-answers
 * ------------------------------------------------------------------------------------------ */

/** A session answer as the Inbox stores it: `session_link/<file id>`, the pick in the resolution. */
const addSessionAnswer = ({ file, pick = 45, state = 'archived', appliedAt = null, resolution = { session_id: pick }, closedItself = false } = {}) =>
  db
    .query(
      `insert into public.attention_items (kind, course_id, entity, ref, field, state, resolved_at, resolution, applied_at, decision, to_value)
       values ('stack_must_confirm', 'ist323', 'bb_file', $1, 'session_id', $2, now(), $3::jsonb, $4::timestamptz,
               case when $2 = 'archived' then $5::jsonb end, '[44, 45]'::jsonb)
       returning id`,
      [`session_link/${file}`, state, JSON.stringify(resolution), appliedAt, JSON.stringify(closedItself ? { closed_itself: true } : { schema: DECISION_SCHEMA })],
    )
    .then((row) => row.rows[0].id);

const addFile = (id, { session = null, superseded = null } = {}) => db.query('insert into public.bb_files (id, session_id, superseded_by) values ($1, $2, $3)', [id, session, superseded]);

const addSupersede = ({ file, state, candidates = [12, 13], closedItself = false }) =>
  db.query(
    `insert into public.attention_items (kind, course_id, entity, ref, field, state, to_value, decision)
     values ('stack_must_confirm', 'ist323', 'bb_file', $1, 'superseded_by', $2, $3::jsonb, case when $2 = 'archived' then $4::jsonb end)`,
    [`supersede/${file}`, state, JSON.stringify(candidates), JSON.stringify(closedItself ? { closed_itself: true } : { schema: DECISION_SCHEMA })],
  );

const transformParams = { since: SINCE };

test('transform-answers: passes on no rows at all, and says so in its counts; a stamped answer is counted; one without the stamp, or a re-asked question, fails', async () => {
  const none = await prove('transform-answers', transformParams);
  assert.equal(none.code, EXIT.pass, none.why);
  assert.deepEqual(none.detail, {
    session_answers_with_pick_on_file: 0, session_answers_unstamped: 0, session_answers_stamped_since_start: 0, supersede_items_looked_at: 0, supersede_reasked: 0,
  });

  // The backfill stamped an answer before the run; the fold stamped another one during it.
  await addFile(101, { session: 45 });
  await addFile(102, { session: 44 });
  await addSessionAnswer({ file: 101, pick: 45, appliedAt: BEFORE_RUN });
  await addSessionAnswer({ file: 102, pick: 44, appliedAt: IN_RUN });
  const stamped = await prove('transform-answers', transformParams);
  assert.equal(stamped.code, EXIT.pass, stamped.why);
  assert.deepEqual([stamped.detail.session_answers_with_pick_on_file, stamped.detail.session_answers_unstamped, stamped.detail.session_answers_stamped_since_start], [2, 0, 1]);

  // None of these is a session answer whose pick the file carries: "none", another pick, an unlinked file, a replaced file, an answer that closed itself.
  await addFile(103, { session: null });
  await addFile(104, { session: 44, superseded: 101 });
  await addFile(105, { session: 45 });
  await addSessionAnswer({ file: 103, pick: 45 });
  await addSessionAnswer({ file: 104, pick: 44 });
  await addSessionAnswer({ file: 105, resolution: { accept: 'none' } });
  await addSessionAnswer({ file: 105, pick: 44 });
  await addSessionAnswer({ file: 105, pick: 45, closedItself: true });
  await addSessionAnswer({ file: 105, pick: 45, state: 'dismissed' });
  assert.equal((await prove('transform-answers', transformParams)).detail.session_answers_with_pick_on_file, 2);
  assert.equal((await prove('transform-answers', transformParams)).code, EXIT.pass);

  // A pick the file carries and no stamp on the answer.
  await addSessionAnswer({ file: 105, pick: 45 });
  const unstamped = await prove('transform-answers', transformParams);
  assert.deepEqual([unstamped.code, unstamped.detail.session_answers_with_pick_on_file, unstamped.detail.session_answers_unstamped], [EXIT.fail, 3, 1]);
  await transformAnswersCase2();
});

/** a supersede question open beside an archived answer for the same candidates is a question asked again, and fails */
async function transformAnswersCase2() {
  await rebuilt(async () => {});
  // An open question alone, or beside an answer for other candidates or one that closed itself, is not asked again.
  await addSupersede({ file: 7, state: 'open' });
  await addSupersede({ file: 8, state: 'open' });
  await addSupersede({ file: 8, state: 'archived', candidates: [20, 21] });
  await addSupersede({ file: 9, state: 'open' });
  await addSupersede({ file: 9, state: 'archived', closedItself: true });
  const fine = await prove('transform-answers', transformParams);
  assert.equal(fine.code, EXIT.pass, fine.why);
  assert.deepEqual([fine.detail.supersede_items_looked_at, fine.detail.supersede_reasked], [5, 0]);
  await addSupersede({ file: 7, state: 'archived' });
  const asked = await prove('transform-answers', transformParams);
  assert.deepEqual([asked.code, asked.detail.supersede_reasked], [EXIT.fail, 1]);
}
