-- bb2dash :: db/tests/phase14_091_sync_runner.sql
-- Phase 14 (docs/planning/sprint-2/briefs/100_PHASE14_containers.md), tasks 6, 11 and 13. Worker
-- W-55. Tests migration 091 (the role `sync_runner`, `agent_requests.claim_attempts`, the twelve
-- SECURITY DEFINER functions and the helper `sync_login_sync_due`) and 094 (the test role's
-- membership in `sync_runner`, inherit false).
--
-- Runs behind its loader, `db/tests/phase14_load_crawl_v4.sql` (generated by
-- `db/fixtures/phase14/scrub_crawl.mjs`), which opens the transaction and lands the scrubbed
-- recorded crawl's nine `bb_raw` rows under the fixture run id 00000000-1491-4000-8000-000000000001.
--
--   0. installed and shaped as the Contract freezes it
--   1. setup (not an assertion): every open sync row is cancelled inside this transaction, and a
--      real `done` sync on today's New York date or on the dates section 9 names is marked failed,
--      so the queue reads and the login trigger see only this unit's rows whatever prod holds
--   2. the fixture's nine rows loaded a second time under the same run id insert 0 rows
--   3. claim -> register -> close: `sync_next`, `sync_claim` (and a lost claim), `sync_register_run`
--      (and its five refusals), `sync_run_outcome`, `sync_close` appending its lines
--   4. the 42501 on a quarantined run id
--   5. `sync_close`'s refusals: other transitions, another claimant, a report without array lines
--   6. the login item: two `login_required` closes leave one open item; `sync_login_ok()` archives
--      it with 114's closed_itself record; a third close opens exactly one new item;
--      `sync_login_required()` twice is one item, and a `login_required` close after it adds none
--   7. the dead-letter sweep: a 21-minute claim and a third-claim row are flagged once, a 19-minute
--      one is not, state never changes, and a second sweep flags nothing
--   8. requeue on start: an unregistered first-claim orphan goes back to queued; a registered row,
--      a row at 3 claims and another claimant's row stay claimed
--   9. `sync_enqueue`: twice is one id; the login trigger and `sync_login_sync_due` on New York
--      dates, across the 2026-11-01 fall-back; 'scheduled' is refused
--  10. the file pair: `sync_file_worklist` lists an unstored row; `sync_file_stored` writes the
--      function's own prefixes once, and refuses a relpath or key that is not the row's
--  11. privileges: as `sync_runner` the three tables raise 42501 and the helper raises 42501; anon
--      and authenticated execute none of the thirteen; no default ACL names `sync_runner`
--
-- Every function call is made under `set local role sync_runner` (094), the way the runner makes it;
-- the setup and the reads that check a call's effect run as the session role. Fixture run ids are
-- `00000000-1491-4000-8000-…`, never a real crawl's.
--
-- RUN IT: `node scripts/db-test.mjs --only phase14_091_sync_runner.sql`. A failing assertion
-- raises; a pass ends with one row reading `phase14_091: PASS`. NOTHING IS COMMITTED: the loader
-- opens the transaction and this file's last statement is `rollback`.

create temp table _t14 (label text primary key, id bigint, run_id uuid) on commit drop;

-- =============================================================================================
-- 0. Installed, and shaped as the Contract freezes it
-- =============================================================================================
do $$
declare
  v_fail text[] := '{}';
  r      record;
  f      text;
  v_fns  text[] := array[
    'public.sync_next()',
    'public.sync_claim(bigint)',
    'public.sync_requeue_orphans()',
    'public.sync_register_run(bigint, uuid)',
    'public.sync_run_outcome(uuid)',
    'public.sync_file_worklist()',
    'public.sync_file_stored(bigint, text, text, text, integer, text, text)',
    'public.sync_close(bigint, text, jsonb)',
    'public.sync_sweep_stale()',
    'public.sync_enqueue(text)',
    'public.sync_login_ok()',
    'public.sync_login_required()'];
begin
  if not exists (select 1 from pg_roles where rolname = 'sync_runner') then
    raise exception 'FAIL phase14_091: migration 091 is not applied (no role sync_runner)';
  end if;
  foreach f in array v_fns || 'public.sync_login_sync_due(timestamp with time zone)'::text loop
    if to_regprocedure(f) is null then
      raise exception 'FAIL phase14_091: migration 091 is not applied (% is missing)', f;
    end if;
  end loop;

  select rolcanlogin, rolinherit, rolbypassrls, rolsuper, rolcreaterole, rolcreatedb, rolreplication
    into r from pg_roles where rolname = 'sync_runner';
  if not r.rolcanlogin then v_fail := v_fail || 'sync_runner cannot log in'::text; end if;
  if r.rolinherit then v_fail := v_fail || 'sync_runner inherits'::text; end if;
  if r.rolbypassrls then v_fail := v_fail || 'sync_runner bypasses RLS'::text; end if;
  if r.rolsuper or r.rolcreaterole or r.rolcreatedb or r.rolreplication then
    v_fail := v_fail || 'sync_runner holds superuser, createrole, createdb or replication'::text;
  end if;

  if not exists (select 1 from information_schema.columns
                  where table_schema = 'public' and table_name = 'agent_requests'
                    and column_name = 'claim_attempts' and data_type = 'smallint'
                    and is_nullable = 'NO' and column_default = '0') then
    v_fail := v_fail || 'agent_requests.claim_attempts is not smallint not null default 0'::text;
  end if;

  foreach f in array v_fns || 'public.sync_login_sync_due(timestamp with time zone)'::text loop
    select p.prosecdef, l.lanname, pg_get_userbyid(p.proowner) as owner,
           coalesce(p.proconfig, '{}') as cfg, obj_description(p.oid, 'pg_proc') as note,
           p.provolatile
      into r
      from pg_proc p join pg_language l on l.oid = p.prolang
     where p.oid = f::regprocedure;
    if not r.prosecdef then v_fail := v_fail || format('%s is not security definer', f); end if;
    if r.lanname <> 'plpgsql' then v_fail := v_fail || format('%s is not plpgsql', f); end if;
    if r.owner <> 'postgres' then v_fail := v_fail || format('%s is owned by %s', f, r.owner); end if;
    if not r.cfg @> array['search_path=public, pg_temp'] then
      v_fail := v_fail || format('%s does not pin search_path = public, pg_temp', f);
    end if;
    if r.note is null then v_fail := v_fail || format('%s has no comment', f); end if;
  end loop;

  if (select provolatile from pg_proc
       where oid = 'public.sync_login_sync_due(timestamp with time zone)'::regprocedure) <> 's' then
    v_fail := v_fail || 'sync_login_sync_due is not stable'::text;
  end if;

  -- The twelve are exactly what sync_runner can run with the owner's rights (task 7's check).
  if (select string_agg(p.proname, ',' order by p.proname)
        from pg_proc p join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public' and p.prosecdef
         and has_function_privilege('sync_runner', p.oid, 'execute'))
     is distinct from
     'sync_claim,sync_close,sync_enqueue,sync_file_stored,sync_file_worklist,sync_login_ok,'
     'sync_login_required,sync_next,sync_register_run,sync_requeue_orphans,sync_run_outcome,'
     'sync_sweep_stale' then
    v_fail := v_fail || 'sync_runner can execute a SECURITY DEFINER function beyond the twelve, or lacks one'::text;
  end if;

  if cardinality(v_fail) > 0 then
    raise exception 'FAIL phase14_091 (shape): %', array_to_string(v_fail, '; ');
  end if;
end $$;

-- =============================================================================================
-- 1. Setup (not an assertion)
-- =============================================================================================
-- An open real sync would be the one `sync_next()` and `sync_enqueue` return; a real `done` sync
-- on today's New York date, or on the dates section 9 names, would make the login trigger queue
-- nothing. Both are changed inside this transaction only; the rollback restores them.
update agent_requests set state = 'cancelled'
 where kind = 'sync' and state in ('queued', 'claimed');

update agent_requests set state = 'failed'
 where kind = 'sync' and state = 'done'
   and ((finished_at at time zone 'America/New_York')::date
          = (now() at time zone 'America/New_York')::date
        or (finished_at >= '2026-10-30 00:00Z' and finished_at < '2026-11-04 00:00Z'));

-- =============================================================================================
-- 2. The recorded crawl, loaded a second time under the same run id, inserts nothing
-- =============================================================================================
do $$
declare
  v_n int;
begin
  select count(*) into v_n from bb_raw where run_id = '00000000-1491-4000-8000-000000000001';
  if v_n <> 9 then
    raise exception 'FAIL 2: the loader landed % bb_raw rows, expected 9', v_n;
  end if;

  insert into bb_raw (run_id, kind, bb_course_id, payload, captured_at)
  select '00000000-1491-4000-8000-000000000001', f.kind, f.bb_course_id, f.payload, f.captured_at
    from _fx14_raw f
  on conflict do nothing;
  get diagnostics v_n = row_count;
  if v_n <> 0 then
    raise exception 'FAIL 2: the second load inserted % rows, expected 0', v_n;
  end if;
end $$;

-- =============================================================================================
-- 3. claim -> register -> outcome -> close, and the refusals on the way
-- =============================================================================================
do $$
declare
  v_a    bigint;   -- the request the runner works
  v_b    bigint;   -- a second queued request, newer
  v_t    bigint;   -- a transform request
  v_o    bigint;   -- another claimant's sync request
  v_run  uuid := '00000000-1491-4000-8000-000000000003';
  v_id   bigint;
  v_ok   boolean;
  v_out  record;
  v_req  record;
  v_run_id bigint;
  v_changes jsonb;
begin
  insert into agent_requests (kind, scope, state, created_at, note)
  values ('sync', 'all', 'queued', now() - interval '2 minutes', 'phase14_091 A')
  returning id into v_a;
  insert into agent_requests (kind, scope, state, created_at, note)
  values ('sync', 'all', 'queued', now() - interval '1 minute', 'phase14_091 B')
  returning id into v_b;
  insert into agent_requests (kind, scope, state, note)
  values ('transform', 'all', 'queued', 'phase14_091 T') returning id into v_t;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, note)
  values ('sync', 'all', 'claimed', now(), 'bb-sync session', 'phase14_091 O') returning id into v_o;

  set local role sync_runner;
  select n.id into v_id from sync_next() n;
  reset role;
  if v_id is distinct from v_a then
    raise exception 'FAIL 3: sync_next() returned %, expected the oldest queued sync %', v_id, v_a;
  end if;

  -- The claim, and the claims that must be refused.
  set local role sync_runner;
  v_ok := sync_claim(v_a);
  reset role;
  if not v_ok then raise exception 'FAIL 3: sync_claim(A) returned false'; end if;
  select state, claimed_by, claim_attempts, claimed_at into v_req from agent_requests where id = v_a;
  if v_req.state <> 'claimed' or v_req.claimed_by <> 'sync-runner' or v_req.claim_attempts <> 1
     or v_req.claimed_at is null then
    raise exception 'FAIL 3: after the claim A reads %', row_to_json(v_req);
  end if;

  set local role sync_runner;
  v_ok := sync_claim(v_a);                     -- lost: already claimed
  reset role;
  if v_ok then raise exception 'FAIL 3: a second sync_claim(A) returned true'; end if;
  set local role sync_runner;
  v_ok := sync_claim(v_t);                     -- not a sync row
  reset role;
  if v_ok then raise exception 'FAIL 3: sync_claim on a transform request returned true'; end if;
  set local role sync_runner;
  v_ok := sync_claim(-1);                      -- no such row
  reset role;
  if v_ok then raise exception 'FAIL 3: sync_claim on a missing id returned true'; end if;
  if (select claim_attempts from agent_requests where id = v_a) <> 1 then
    raise exception 'FAIL 3: a lost claim moved claim_attempts';
  end if;

  -- Register-first: the trigger opens the running row.
  set local role sync_runner;
  v_ok := sync_register_run(v_a, v_run);
  reset role;
  if not v_ok then raise exception 'FAIL 3: sync_register_run(A) returned false'; end if;
  if (select run_id from agent_requests where id = v_a) is distinct from v_run then
    raise exception 'FAIL 3: A does not carry the registered run id';
  end if;

  set local role sync_runner;
  select o.sync_run_id, o.status, o.summary into v_out from sync_run_outcome(v_run) o;
  reset role;
  if v_out.status is distinct from 'running' then
    raise exception 'FAIL 3: sync_run_outcome after register reads %, expected running', v_out.status;
  end if;
  v_run_id := v_out.sync_run_id;

  -- The five refusals: already registered, a run id on another request, not claimed, not sync,
  -- another claimant.
  set local role sync_runner;
  v_ok := sync_register_run(v_a, '00000000-1491-4000-8000-000000000004');
  reset role;
  if v_ok then raise exception 'FAIL 3: a second registration on A returned true'; end if;

  set local role sync_runner;
  v_ok := sync_claim(v_b);
  v_ok := sync_register_run(v_b, v_run);
  reset role;
  if v_ok then raise exception 'FAIL 3: a run id already on A registered on B'; end if;

  update agent_requests set state = 'queued', claimed_at = null, claimed_by = null where id = v_b;
  set local role sync_runner;
  v_ok := sync_register_run(v_b, '00000000-1491-4000-8000-000000000005');
  reset role;
  if v_ok then raise exception 'FAIL 3: a queued request was registered'; end if;

  update agent_requests set state = 'claimed', claimed_at = now(), claimed_by = 'sync-runner'
   where id = v_t;
  set local role sync_runner;
  v_ok := sync_register_run(v_t, '00000000-1491-4000-8000-000000000006');
  reset role;
  if v_ok then raise exception 'FAIL 3: a transform request was registered'; end if;

  set local role sync_runner;
  v_ok := sync_register_run(v_o, '00000000-1491-4000-8000-000000000007');
  reset role;
  if v_ok then raise exception 'FAIL 3: another claimant''s request was registered'; end if;

  -- The fold, simulated: the run finishes with one change line of its own.
  update sync_runs set status = 'ok', finished_at = clock_timestamp(),
                       summary = '{"changes": ["fold line"], "errors": []}'::jsonb
   where id = v_run_id;

  set local role sync_runner;
  select o.status into v_out from sync_run_outcome(v_run) o;
  reset role;
  if v_out.status is distinct from 'ok' then
    raise exception 'FAIL 3: sync_run_outcome after the fold reads %, expected ok', v_out.status;
  end if;

  set local role sync_runner;
  perform sync_close(v_a, 'done',
    '{"lines": ["runner line 1", "runner line 2"], "error": null,
      "files": {"pulled": 0, "not_pulled": []}, "claim_attempts": 1}'::jsonb);
  reset role;

  select state, finished_at, result, sync_run_id into v_req from agent_requests where id = v_a;
  if v_req.state <> 'done' or v_req.finished_at is null or v_req.sync_run_id is distinct from v_run_id
     or v_req.result->'lines' <> '["runner line 1", "runner line 2"]'::jsonb then
    raise exception 'FAIL 3: after close A reads %', row_to_json(v_req);
  end if;
  select summary->'changes' into v_changes from sync_runs where id = v_run_id;
  if v_changes <> '["fold line", "runner line 1", "runner line 2"]'::jsonb then
    raise exception 'FAIL 3: sync_close did not append its lines; changes are %', v_changes;
  end if;

  insert into _t14 values ('A', v_a, v_run), ('B', v_b, null), ('O', v_o, null);
end $$;

-- =============================================================================================
-- 4. A quarantined run id is refused with 42501
-- =============================================================================================
do $$
declare
  v_q   uuid := '00000000-1491-4000-8000-000000000008';
  v_c   bigint;
  v_ok  boolean;
  v_raised boolean := false;
begin
  insert into sync_runs (run_id, status, started_at, finished_at, trigger, source, scope, notes)
  values (v_q, 'failed', now(), now(), 'scheduled', 'blackboard', 'unregistered', 'phase14_091 quarantine');
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now(), 'sync-runner', 1, 'phase14_091 C') returning id into v_c;

  begin
    set local role sync_runner;
    v_ok := sync_register_run(v_c, v_q);
  exception when insufficient_privilege then
    v_raised := true;
  end;
  reset role;
  if not v_raised then
    raise exception 'FAIL 4: registering a quarantined run id did not raise 42501';
  end if;
  if (select run_id from agent_requests where id = v_c) is not null then
    raise exception 'FAIL 4: the quarantined run id was written onto the request';
  end if;
end $$;

-- =============================================================================================
-- 5. sync_close refuses every other transition and a malformed report
-- =============================================================================================
do $$
declare
  v_a bigint := (select id from _t14 where label = 'A');
  v_o bigint := (select id from _t14 where label = 'O');
  v_q bigint;
  v_case record;
  v_raised boolean;
begin
  insert into agent_requests (kind, scope, state, note)
  values ('sync', 'all', 'queued', 'phase14_091 Q5') returning id into v_q;

  for v_case in
    select * from (values
      ('done -> done',            v_a, 'done',    '{"lines": []}'),
      ('done -> failed',          v_a, 'failed',  '{"lines": []}'),
      ('queued -> done',          v_q, 'done',    '{"lines": []}'),
      ('another claimant',        v_o, 'done',    '{"lines": []}'),
      ('state cancelled',         v_q, 'cancelled', '{"lines": []}'),
      ('no lines',                v_q, 'failed',  '{"error": "x"}'),
      ('lines not an array',      v_q, 'failed',  '{"lines": "x"}'),
      ('a line not text',         v_q, 'failed',  '{"lines": [1]}'),
      ('report not an object',    v_q, 'failed',  '["x"]'),
      ('missing request',         -1::bigint, 'failed', '{"lines": []}')
    ) t(label, id, st, rep)
  loop
    v_raised := false;
    begin
      set local role sync_runner;
      perform sync_close(v_case.id, v_case.st, v_case.rep::jsonb);
    exception when others then
      v_raised := true;
    end;
    reset role;
    if not v_raised then
      raise exception 'FAIL 5: sync_close accepted %', v_case.label;
    end if;
  end loop;

  if (select state from agent_requests where id = v_q) <> 'queued'
     or (select state from agent_requests where id = v_o) <> 'claimed' then
    raise exception 'FAIL 5: a refused close changed a request';
  end if;
end $$;

-- =============================================================================================
-- 6. The login item: raised once, closed by the login check, raised fresh after
-- =============================================================================================
do $$
declare
  v_r1 bigint; v_r2 bigint; v_r3 bigint; v_r4 bigint;
  v_item1 bigint; v_item2 bigint; v_item3 bigint; v_item4 bigint;
  v_n int;
  v_closed int;
  v_row record;
  v_rep jsonb := '{"lines": ["login required"], "error": "login_required",
                   "files": {"pulled": 0, "not_pulled": []}, "claim_attempts": 0}';
begin
  insert into agent_requests (kind, scope, state, note) values
    ('sync', 'all', 'queued', 'phase14_091 L1') returning id into v_r1;
  insert into agent_requests (kind, scope, state, note) values
    ('sync', 'all', 'queued', 'phase14_091 L2') returning id into v_r2;

  set local role sync_runner;
  perform sync_close(v_r1, 'failed', v_rep);
  perform sync_close(v_r2, 'failed', v_rep);
  reset role;

  if (select state from agent_requests where id = v_r1) <> 'failed'
     or (select state from agent_requests where id = v_r2) <> 'failed' then
    raise exception 'FAIL 6: a login_required close did not move queued -> failed';
  end if;
  select count(*), min(id) into v_n, v_item1 from attention_items
   where kind = 'stack_must_confirm' and ref = 'sync-login-required' and state = 'open';
  if v_n <> 1 then
    raise exception 'FAIL 6: two login_required closes left % open login items, expected 1', v_n;
  end if;
  if (select question from attention_items where id = v_item1)
     <> 'Blackboard login needed — open http://127.0.0.1:6080/vnc.html and sign in with Duo' then
    raise exception 'FAIL 6: the login item''s question is not the frozen text';
  end if;

  set local role sync_runner;
  v_closed := sync_login_ok();
  reset role;
  if v_closed <> 1 then
    raise exception 'FAIL 6: sync_login_ok() returned %, expected 1', v_closed;
  end if;
  select * into v_row from attention_items where id = v_item1;
  if v_row.state <> 'archived' or v_row.archived_by <> 'sync-runner' or v_row.archived_at is null
     or v_row.decision->>'closed_itself' <> 'true'
     or v_row.decision->>'rule' <> 'login check passed'
     or v_row.decision->>'trigger' <> 'sync_login_ok'
     or not (v_row.decision ? 'sync_run_id') or v_row.decision->'sync_run_id' <> 'null'::jsonb then
    raise exception 'FAIL 6: after sync_login_ok the item reads state %, archived_by %, decision %',
      v_row.state, v_row.archived_by, v_row.decision;
  end if;

  set local role sync_runner;
  v_closed := sync_login_ok();
  reset role;
  if v_closed <> 0 then
    raise exception 'FAIL 6: a second sync_login_ok() closed %, expected 0', v_closed;
  end if;

  insert into agent_requests (kind, scope, state, note) values
    ('sync', 'all', 'queued', 'phase14_091 L3') returning id into v_r3;
  set local role sync_runner;
  perform sync_close(v_r3, 'failed', v_rep);
  reset role;
  select count(*), min(id) into v_n, v_item2 from attention_items
   where kind = 'stack_must_confirm' and ref = 'sync-login-required' and state = 'open';
  if v_n <> 1 or v_item2 = v_item1 then
    raise exception 'FAIL 6: the third login_required close left % open items (first %, now %), expected exactly one new item',
      v_n, v_item1, v_item2;
  end if;

  -- sync_login_required(): twice is one item, and a login_required close after it adds none.
  set local role sync_runner;
  perform sync_login_ok();
  v_item3 := sync_login_required();
  v_item4 := sync_login_required();
  reset role;
  if v_item3 is null or v_item3 is distinct from v_item4 then
    raise exception 'FAIL 6: sync_login_required() twice returned % and %', v_item3, v_item4;
  end if;
  if (select state from attention_items where id = v_item3) <> 'open' then
    raise exception 'FAIL 6: sync_login_required() returned an item that is not open';
  end if;

  insert into agent_requests (kind, scope, state, note) values
    ('sync', 'all', 'queued', 'phase14_091 L4') returning id into v_r4;
  set local role sync_runner;
  perform sync_close(v_r4, 'failed', v_rep);
  reset role;
  select count(*) into v_n from attention_items
   where kind = 'stack_must_confirm' and ref = 'sync-login-required' and state = 'open';
  if v_n <> 1 then
    raise exception 'FAIL 6: a login_required close after sync_login_required() left % open items', v_n;
  end if;

  -- A close that is not login_required raises nothing.
  set local role sync_runner;
  perform sync_login_ok();
  reset role;
  insert into agent_requests (kind, scope, state, note) values
    ('sync', 'all', 'queued', 'phase14_091 L5') returning id into v_r4;
  set local role sync_runner;
  perform sync_close(v_r4, 'failed', '{"lines": ["crawl threw"], "error": "crawl failed"}'::jsonb);
  reset role;
  if exists (select 1 from attention_items
              where kind = 'stack_must_confirm' and ref = 'sync-login-required' and state = 'open') then
    raise exception 'FAIL 6: a close whose error is not login_required raised the login item';
  end if;
end $$;

-- =============================================================================================
-- 7. The dead-letter sweep
-- =============================================================================================
do $$
declare
  v_s21 bigint; v_s3 bigint; v_f21 bigint; v_s19 bigint;
  v_n int;
  v_bad text;
begin
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now() - interval '21 minutes', 'sync-runner', 1, 'phase14_091 S21')
  returning id into v_s21;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now(), 'sync-runner', 3, 'phase14_091 S3')
  returning id into v_s3;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, note)
  values ('inbox_feedback', 'all', 'claimed', now() - interval '21 minutes', 'inbox-apply', 'phase14_091 F21')
  returning id into v_f21;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now() - interval '19 minutes', 'sync-runner', 1, 'phase14_091 S19')
  returning id into v_s19;

  set local role sync_runner;
  v_n := sync_sweep_stale();
  reset role;
  if v_n < 3 then
    raise exception 'FAIL 7: the first sweep flagged %, expected at least this unit''s 3', v_n;
  end if;

  select string_agg(a.note, ', ') into v_bad from agent_requests a
   where a.id in (v_s21, v_s3, v_f21)
     and (a.state <> 'claimed' or a.result->>'dead_lettered_at' is null
          or (select count(*) from attention_items i
               where i.kind = 'stack_must_confirm' and i.ref = 'agent_request:' || a.id
                 and i.state = 'open' and i.entity = 'agent_request' and i.course_id is null) <> 1);
  if v_bad is not null then
    raise exception 'FAIL 7: not flagged once with state kept: %', v_bad;
  end if;
  if (select result from agent_requests where id = v_s19) is not null
     or exists (select 1 from attention_items where ref = 'agent_request:' || v_s19) then
    raise exception 'FAIL 7: the 19-minute claim was flagged';
  end if;

  set local role sync_runner;
  v_n := sync_sweep_stale();
  reset role;
  if v_n <> 0 then
    raise exception 'FAIL 7: the second sweep flagged %, expected 0', v_n;
  end if;
  if (select count(*) from attention_items
       where ref in ('agent_request:' || v_s21, 'agent_request:' || v_s3, 'agent_request:' || v_f21)) <> 3 then
    raise exception 'FAIL 7: the second sweep raised another item';
  end if;
end $$;

-- =============================================================================================
-- 8. Requeue on start
-- =============================================================================================
do $$
declare
  v_orphan bigint; v_reg bigint; v_full bigint; v_other bigint;
  v_n int;
  v_row record;
begin
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now(), 'sync-runner', 1, 'phase14_091 R1') returning id into v_orphan;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, run_id, note)
  values ('sync', 'all', 'claimed', now(), 'sync-runner', 1, '00000000-1491-4000-8000-000000000009', 'phase14_091 R2')
  returning id into v_reg;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now(), 'sync-runner', 3, 'phase14_091 R3') returning id into v_full;
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, claim_attempts, note)
  values ('sync', 'all', 'claimed', now(), 'bb-sync session', 0, 'phase14_091 R4') returning id into v_other;

  set local role sync_runner;
  v_n := sync_requeue_orphans();
  reset role;
  if v_n < 1 then raise exception 'FAIL 8: sync_requeue_orphans() returned %', v_n; end if;

  select state, claimed_at, claimed_by, claim_attempts into v_row from agent_requests where id = v_orphan;
  if v_row.state <> 'queued' or v_row.claimed_at is not null or v_row.claimed_by is not null
     or v_row.claim_attempts <> 1 then
    raise exception 'FAIL 8: the orphan reads %', row_to_json(v_row);
  end if;
  if (select state from agent_requests where id = v_reg) <> 'claimed' then
    raise exception 'FAIL 8: a registered row was requeued';
  end if;
  if (select state from agent_requests where id = v_full) <> 'claimed' then
    raise exception 'FAIL 8: a row at 3 claims was requeued';
  end if;
  if (select state from agent_requests where id = v_other) <> 'claimed' then
    raise exception 'FAIL 8: another claimant''s row was requeued';
  end if;
end $$;

-- =============================================================================================
-- 9. sync_enqueue and the login trigger
-- =============================================================================================
-- Sections 3-8 left open sync rows, and section 3 closed one `done` today; the queue starts empty
-- again here, with no done sync on today's New York date.
update agent_requests set state = 'cancelled'
 where kind = 'sync' and state in ('queued', 'claimed');
update agent_requests set state = 'failed'
 where kind = 'sync' and state = 'done'
   and (finished_at at time zone 'America/New_York')::date
       = (now() at time zone 'America/New_York')::date;

do $$
declare
  v_j1 bigint; v_j2 bigint; v_l1 bigint; v_l2 bigint; v_l3 bigint; v_j3 bigint;
  v_before int;
  v_raised boolean;
  v_bad text;
  v_case record;
begin
  -- 'just' twice is one id.
  set local role sync_runner;
  v_j1 := sync_enqueue('just');
  v_j2 := sync_enqueue('just');
  reset role;
  if v_j1 is null or v_j1 is distinct from v_j2 then
    raise exception 'FAIL 9: sync_enqueue(''just'') twice returned % and %', v_j1, v_j2;
  end if;
  if (select params->>'trigger' from agent_requests where id = v_j1) is distinct from 'just'
     or (select state from agent_requests where id = v_j1) <> 'queued'
     or (select kind from agent_requests where id = v_j1) <> 'sync' then
    raise exception 'FAIL 9: the just request is not a queued sync with params.trigger just';
  end if;

  -- 'login' with one open returns that id.
  set local role sync_runner;
  v_l1 := sync_enqueue('login');
  reset role;
  if v_l1 is distinct from v_j1 then
    raise exception 'FAIL 9: sync_enqueue(''login'') with one open returned %, expected %', v_l1, v_j1;
  end if;

  -- 'login' with none done today queues a new one.
  update agent_requests set state = 'cancelled' where id = v_j1;
  set local role sync_runner;
  v_l2 := sync_enqueue('login');
  reset role;
  if v_l2 is null or v_l2 = v_j1
     or (select params->>'trigger' from agent_requests where id = v_l2) is distinct from 'login' then
    raise exception 'FAIL 9: sync_enqueue(''login'') with no sync done today returned %', v_l2;
  end if;

  -- 'login' with one done today (New York) returns null and inserts nothing.
  update agent_requests set state = 'done', claimed_at = now(), claimed_by = 'sync-runner',
                            finished_at = now()
   where id = v_l2;
  select count(*) into v_before from agent_requests where kind = 'sync';
  set local role sync_runner;
  v_l3 := sync_enqueue('login');
  reset role;
  if v_l3 is not null or (select count(*) from agent_requests where kind = 'sync') <> v_before then
    raise exception 'FAIL 9: sync_enqueue(''login'') after a done sync today returned % and inserted % row(s)',
      v_l3, (select count(*) from agent_requests where kind = 'sync') - v_before;
  end if;

  -- 'just' is Stack's own press: it still queues on a day that has a done sync.
  set local role sync_runner;
  v_j3 := sync_enqueue('just');
  reset role;
  if v_j3 is null then
    raise exception 'FAIL 9: sync_enqueue(''just'') after a done sync today queued nothing';
  end if;
  -- Out of the way of the date cases below, whatever day the suite runs on.
  update agent_requests set state = 'cancelled' where id = v_l2;

  -- 'scheduled' (dropped with 092 on 2026-10-03), an unknown word and null are refused.
  for v_case in select * from (values ('scheduled'), ('nightly'), (null)) t(trig) loop
    v_raised := false;
    begin
      set local role sync_runner;
      perform sync_enqueue(v_case.trig);
    exception when others then
      v_raised := true;
    end;
    reset role;
    if not v_raised then
      raise exception 'FAIL 9: sync_enqueue(%) was accepted', coalesce(quote_literal(v_case.trig), 'null');
    end if;
  end loop;

end $$;

-- sync_login_sync_due reads the New York date, not UTC, across the 2026-11-01 fall-back. Each case
-- is one done sync finished at `fin`, then the helper at `at`, called as the test role: 094 makes
-- it the helper's one grantee besides the owner, so the instant can be fixed (sync_enqueue only
-- ever passes now()).
do $$
declare
  v_case record;
  v_id   bigint;
  v_got  boolean;
  v_bad  text[] := '{}';
begin
  for v_case in
    select * from (values
      ('2026-10-31 03:30Z'::timestamptz, '2026-10-31 12:00Z'::timestamptz, true),   -- 23:30 on the 30th (EDT)
      ('2026-10-31 13:00Z'::timestamptz, '2026-10-31 12:00Z'::timestamptz, false),  -- 09:00 on the 31st
      ('2026-11-02 04:30Z'::timestamptz, '2026-11-02 12:00Z'::timestamptz, true),   -- 23:30 on the 1st (EST)
      ('2026-11-02 05:30Z'::timestamptz, '2026-11-02 12:00Z'::timestamptz, false)   -- 00:30 on the 2nd (EST)
    ) t(fin, at, want)
  loop
    insert into agent_requests (kind, scope, state, claimed_at, claimed_by, finished_at, note)
    values ('sync', 'all', 'done', v_case.fin, 'sync-runner', v_case.fin, 'phase14_091 due case')
    returning id into v_id;
    v_got := sync_login_sync_due(v_case.at);
    if v_got is distinct from v_case.want then
      v_bad := v_bad || format('finished %s, asked at %s: got %s, expected %s',
                               v_case.fin, v_case.at, v_got, v_case.want);
    end if;
    update agent_requests set state = 'cancelled' where id = v_id;
  end loop;

  -- A failed sync, or a done one with no finished_at, is not the day's sync.
  insert into agent_requests (kind, scope, state, claimed_at, claimed_by, finished_at, note)
  values ('sync', 'all', 'failed', '2026-10-31 13:00Z', 'sync-runner', '2026-10-31 13:00Z',
          'phase14_091 due case failed') returning id into v_id;
  if sync_login_sync_due('2026-10-31 12:00Z') is not true then
    v_bad := v_bad || 'a failed sync counted as the day''s done sync'::text;
  end if;
  update agent_requests set state = 'cancelled' where id = v_id;

  if cardinality(v_bad) > 0 then
    raise exception 'FAIL 9: sync_login_sync_due: %', array_to_string(v_bad, '; ');
  end if;
end $$;

-- =============================================================================================
-- 10. The file pair
-- =============================================================================================
do $$
declare
  v_course text := (select id from courses order by id limit 1);
  v_f      bigint;
  v_sub    bigint;
  v_rel    text;
  v_srel   text;
  v_ok     boolean;
  v_row    record;
  v_listed record;
  v_raised boolean;
  v_case   record;
  v_sha    text := repeat('ab', 32);
begin
  insert into bb_files (bb_course_id, course_id, file_name, source_url, captured_at, bucket,
                        text_status, mime_type, notes)
  values ('_w55fx_1', v_course, 'w55 #fixture.pdf',
          'https://blackboard.syracuse.edu/bbcswebdav/xid-w55fx_1', now(), 'lecture_slides',
          'pending', 'application/pdf', 'phase14_091 fixture')
  returning id into v_f;
  insert into bb_files (bb_course_id, course_id, file_name, source_url, captured_at, bucket,
                        text_status, mime_type, attempt_id, notes)
  values ('_w55fx_1', v_course, 'w55-submission.docx',
          'https://blackboard.syracuse.edu/bbcswebdav/xid-w55fx_2', now(), 'my_submissions',
          'pending', 'application/msword', '_w55fx_attempt_9_1', 'phase14_091 fixture')
  returning id into v_sub;
  v_rel  := bb_file_relpath(v_f);
  v_srel := bb_file_relpath(v_sub);

  set local role sync_runner;
  select w.* into v_listed from sync_file_worklist() w where w.id = v_f;
  reset role;
  if v_listed.id is null or v_listed.relpath <> v_rel or v_listed.file_name <> 'w55 #fixture.pdf'
     or v_listed.bucket <> 'lecture_slides' or v_listed.mime <> 'application/pdf'
     or v_listed.source_url <> 'https://blackboard.syracuse.edu/bbcswebdav/xid-w55fx_1' then
    raise exception 'FAIL 10: the worklist row reads %', row_to_json(v_listed);
  end if;

  -- Refused: a relpath that is not the row's, a key that is not the relpath's, a bad sha256, a
  -- text status outside the enum. Each raises; none writes.
  for v_case in
    select * from (values
      ('relpath not the row''s', 'x/' || v_rel, replace('x/' || v_rel, '#', '_'), v_sha, 'extracted'),
      ('key not the relpath''s', v_rel, 'elsewhere/file.pdf', v_sha, 'extracted'),
      ('sha256 not hex',         v_rel, replace(v_rel, '#', '_'), 'nothex', 'extracted'),
      ('text status unknown',    v_rel, replace(v_rel, '#', '_'), v_sha, 'done')
    ) t(label, rel, k, sha, ts)
  loop
    v_raised := false;
    begin
      set local role sync_runner;
      perform sync_file_stored(v_f, v_case.k, v_case.rel, v_case.sha, 2048, 'application/pdf', v_case.ts);
    exception when others then
      v_raised := true;
    end;
    reset role;
    if not v_raised then
      raise exception 'FAIL 10: sync_file_stored accepted %', v_case.label;
    end if;
  end loop;
  if (select storage_path from bb_files where id = v_f) is not null then
    raise exception 'FAIL 10: a refused sync_file_stored wrote the row';
  end if;

  set local role sync_runner;
  v_ok := sync_file_stored(v_f, replace(v_rel, '#', '_'), v_rel, v_sha, 2048, 'application/pdf', 'extracted');
  reset role;
  if not v_ok then raise exception 'FAIL 10: sync_file_stored returned false on an unstored row'; end if;
  select * into v_row from bb_files where id = v_f;
  if v_row.storage_path <> 'bb-files/' || replace(v_rel, '#', '_')
     or v_row.local_path <> 'course context/' || v_rel
     or v_row.sha256 <> v_sha or v_row.bytes <> 2048 or v_row.mime_type <> 'application/pdf'
     or v_row.text_status::text <> 'extracted' or v_row.downloaded_at is null
     or v_row.notes not like 'phase14_091 fixture | bytes pulled ____-__-__ by sync-runner' then
    raise exception 'FAIL 10: the stored row reads storage_path %, local_path %, notes %',
      v_row.storage_path, v_row.local_path, v_row.notes;
  end if;

  set local role sync_runner;
  v_ok := sync_file_stored(v_f, replace(v_rel, '#', '_'), v_rel, v_sha, 2048, 'application/pdf', 'extracted');
  reset role;
  if v_ok then raise exception 'FAIL 10: sync_file_stored wrote a row that already had bytes'; end if;

  set local role sync_runner;
  select w.* into v_listed from sync_file_worklist() w where w.id = v_f;
  reset role;
  if v_listed.id is not null then
    raise exception 'FAIL 10: a stored row is still on the worklist';
  end if;

  -- A submission keeps the mime type Blackboard declared.
  set local role sync_runner;
  v_ok := sync_file_stored(v_sub, replace(v_srel, '#', '_'), v_srel, v_sha, 4096,
                           'application/octet-stream', 'failed');
  reset role;
  if not v_ok or (select mime_type from bb_files where id = v_sub) <> 'application/msword' then
    raise exception 'FAIL 10: a submission''s declared mime type was not kept';
  end if;
end $$;

-- =============================================================================================
-- 11. Privileges
-- =============================================================================================
do $$
declare
  v_t      text;
  v_f      text;
  v_raised boolean;
  v_bad    text[] := '{}';
begin
  -- As sync_runner, the three tables it reaches only through the functions raise 42501.
  foreach v_t in array array['agent_requests', 'bb_files', 'attention_items'] loop
    v_raised := false;
    begin
      set local role sync_runner;
      execute format('select 1 from public.%I limit 1', v_t);
    exception when insufficient_privilege then
      v_raised := true;
    end;
    reset role;
    if not v_raised then v_bad := v_bad || format('sync_runner can read %s', v_t); end if;
    if has_table_privilege('sync_runner', 'public.' || v_t, 'select') then
      v_bad := v_bad || format('has_table_privilege(sync_runner, %s, select) is true', v_t);
    end if;
  end loop;

  -- No table, view or sequence grant at all (task 7's check).
  if (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relkind in ('r', 'v', 'm', 'p')
         and has_table_privilege('sync_runner', c.oid, 'select,insert,update,delete')) <> 0 then
    v_bad := v_bad || 'sync_runner holds a privilege on a public table or view'::text;
  end if;
  -- The CASE keeps has_sequence_privilege off every relation that is not a sequence: the planner
  -- may evaluate it before the relkind filter, and on an index it raises.
  if (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relkind = 'S'
         and case when c.relkind = 'S'
                  then has_sequence_privilege('sync_runner', c.oid, 'usage,select,update')
                  else false end) <> 0 then
    v_bad := v_bad || 'sync_runner holds a privilege on a public sequence'::text;
  end if;

  -- The helper is not sync_runner's to call.
  v_raised := false;
  begin
    set local role sync_runner;
    perform sync_login_sync_due(now());
  exception when insufficient_privilege then
    v_raised := true;
  end;
  reset role;
  if not v_raised then v_bad := v_bad || 'sync_runner can execute sync_login_sync_due'::text; end if;

  -- anon and authenticated execute none of the twelve, nor the helper; sync_runner not the helper.
  foreach v_f in array array[
    'public.sync_next()', 'public.sync_claim(bigint)', 'public.sync_requeue_orphans()',
    'public.sync_register_run(bigint, uuid)', 'public.sync_run_outcome(uuid)',
    'public.sync_file_worklist()',
    'public.sync_file_stored(bigint, text, text, text, integer, text, text)',
    'public.sync_close(bigint, text, jsonb)', 'public.sync_sweep_stale()',
    'public.sync_enqueue(text)', 'public.sync_login_ok()', 'public.sync_login_required()',
    'public.sync_login_sync_due(timestamp with time zone)'] loop
    if has_function_privilege('anon', v_f, 'execute')
       or has_function_privilege('authenticated', v_f, 'execute') then
      v_bad := v_bad || format('anon or authenticated can execute %s', v_f);
    end if;
  end loop;
  if has_function_privilege('sync_runner', 'public.sync_login_sync_due(timestamp with time zone)', 'execute')
     or has_function_privilege('service_role', 'public.sync_login_sync_due(timestamp with time zone)', 'execute') then
    v_bad := v_bad || 'sync_runner or service_role can execute sync_login_sync_due'::text;
  end if;

  -- No default ACL names sync_runner, as owner or grantee.
  if exists (select 1 from pg_default_acl d where d.defaclrole = 'sync_runner'::regrole)
     or exists (select 1 from pg_default_acl d, aclexplode(d.defaclacl) a
                 where a.grantee = 'sync_runner'::regrole) then
    v_bad := v_bad || 'a pg_default_acl row names sync_runner'::text;
  end if;

  -- 094: the test role holds sync_runner with inherit false, and sync_runner holds no role at all.
  if not exists (select 1 from pg_auth_members m
                  where m.roleid = 'sync_runner'::regrole and m.member = 'db_test_runner'::regrole
                    and not m.inherit_option) then
    v_bad := v_bad || 'db_test_runner does not hold sync_runner with inherit false'::text;
  end if;
  if exists (select 1 from pg_auth_members m where m.member = 'sync_runner'::regrole) then
    v_bad := v_bad || 'sync_runner is a member of another role'::text;
  end if;

  if cardinality(v_bad) > 0 then
    raise exception 'FAIL 11: %', array_to_string(v_bad, '; ');
  end if;
end $$;

-- =============================================================================================
-- Pass
-- =============================================================================================
select 'phase14_091: PASS'                                                               as result,
       current_user                                                                      as ran_as,
       (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.prosecdef
           and has_function_privilege('sync_runner', p.oid, 'execute'))                  as runner_functions,
       (select count(*) from bb_raw where run_id = '00000000-1491-4000-8000-000000000001') as fixture_rows;

rollback;
